[package]
name = "graynet"
version = "0.1.1"
description = "GrayNet - I2P Network Launcher"
authors = ["vialolis"]
edition = "2021"

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
lto = true
strip = true

[[bin]]
name = "graynet"
path = "src/main.rs"

[dependencies]
tauri = { version = "1.6", features = [
    "shell-open",
    "path-all",
    "system-tray",
    "custom-protocol",
] }

futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
log = "0.4"
env_logger = "0.11"
sysinfo = "0.29"
reqwest = { version = "0.11", features = ["stream"] }
zip = "0.6"
tokio = { version = "1", features = ["full"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
libc = "0.2"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
ico = "0.3"

[features]
custom-protocol = ["tauri/custom-protocol"]
